# Generated by Codex on 2026-04-28

from django.db import migrations, models


NEW_STATUS_CHOICES = [
    ('payment_not_received', 'Payment Not Received'),
    ('payment_received', 'Payment Received'),
    ('payment_failed', 'Payment Failed'),
    ('preparing', 'Preparing Your Order'),
    ('packed_shipped', 'Packed and Shipped'),
    ('delivered', 'Delivered'),
    ('cancelled', 'Cancelled'),
    ('refunded', 'Refunded'),
]


def forwards(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    OrderStatusHistory = apps.get_model('orders', 'OrderStatusHistory')

    status_map = {
        'pending': 'payment_not_received',
        'confirmed': 'payment_received',
        'processing': 'preparing',
        'shipped': 'packed_shipped',
    }

    for old_status, new_status in status_map.items():
        Order.objects.filter(status=old_status).update(status=new_status)
        OrderStatusHistory.objects.filter(status=old_status).update(status=new_status)


def backwards(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    OrderStatusHistory = apps.get_model('orders', 'OrderStatusHistory')

    status_map = {
        'payment_not_received': 'pending',
        'payment_received': 'confirmed',
        'payment_failed': 'pending',
        'preparing': 'processing',
        'packed_shipped': 'shipped',
    }

    for old_status, new_status in status_map.items():
        Order.objects.filter(status=old_status).update(status=new_status)
        OrderStatusHistory.objects.filter(status=old_status).update(status=new_status)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=NEW_STATUS_CHOICES,
                default='payment_not_received',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=NEW_STATUS_CHOICES, max_length=20),
        ),
    ]
