# Generated by Django 5.0.6 on 2026-05-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_update_order_status_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_link',
            field=models.URLField(blank=True, help_text='Delivery partner tracking URL (shown to customer)', max_length=500, null=True),
        ),
    ]
