# Generated by Django 5.0.6 on 2026-03-30 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='hero_sliders/')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('link_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Sliders',
                'db_table': 'hero_sliders',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='instagram_gallery/')),
                ('link_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instagram Post',
                'verbose_name_plural': 'Instagram Posts',
                'db_table': 'instagram_posts',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
