# Generated by Django 5.0.6 on 2026-03-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_heroslider_instagrampost_product_is_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_quick_pick',
            field=models.BooleanField(default=False),
        ),
    ]
