# Generated by Django 5.0.6 on 2026-04-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_is_new_arrival_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='styling',
            field=models.TextField(blank=True, default=''),
        ),
    ]
