# Generated by Django 5.0.6 on 2026-04-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_styling'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_bestseller', '-updated_at', '-created_at'], name='idx_product_bestseller'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_quick_pick', '-updated_at', '-created_at'], name='idx_product_quickpick'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_new_arrival', '-updated_at', '-created_at'], name='idx_product_newarrival'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='idx_product_active_created'),
        ),
    ]
