# Generated by Django 5.0.6 on 2026-04-17 05:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_discount_text_product_discounted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoatingType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the coating (e.g., 18kt Yellow Gold)', max_length=100, unique=True)),
                ('color_rgb', models.CharField(blank=True, default='#CCCCCC', help_text='Hex or RGB value (e.g., #E5A01D)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coating Type',
                'verbose_name_plural': 'Coating Types',
                'db_table': 'coating_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='coating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.coatingtype'),
        ),
    ]
