# Generated by Django 5.0.6 on 2026-04-19 15:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_composite_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='promotional_banners/')),
                ('link_url', models.CharField(blank=True, default='', max_length=500)),
                ('alt_text', models.CharField(blank=True, default='', help_text='Accessibility alt text for the banner image', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promotional Banner',
                'verbose_name_plural': 'Promotional Banners',
                'db_table': 'promotional_banners',
                'ordering': ['display_order'],
            },
        ),
    ]
