# Generated by Django 5.0.6 on 2026-04-17 05:42

from django.db import migrations

def migrate_coating_types(apps, schema_editor):
    ProductVariant = apps.get_model('products', 'ProductVariant')
    CoatingType = apps.get_model('products', 'CoatingType')

    for variant in ProductVariant.objects.all():
        if variant.metal_type:
            # Create or get CoatingType
            coating, created = CoatingType.objects.get_or_create(
                name=variant.metal_type,
                defaults={'color_rgb': '#CCCCCC'}
            )
            variant.coating = coating
            variant.save()

def reverse_migrate_coating_types(apps, schema_editor):
    pass 

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_coatingtype_productvariant_coating'),
    ]

    operations = [
        migrations.RunPython(migrate_coating_types, reverse_migrate_coating_types),
    ]
