# Generated by Django 5.0.6 on 2026-04-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_promotional_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromotionalBanner',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_text',
            field=models.CharField(blank=True, default='', help_text='e.g. "Save 20%", "Sale"', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set this to override base_price with a discount', max_digits=12, null=True),
        ),
    ]
