# Generated by Django 5.0.6 on 2026-04-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20260417_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='mobile_image',
            field=models.ImageField(
                blank=True,
                help_text='Optional mobile-optimized hero image (recommended portrait ratio like 3:4).',
                null=True,
                upload_to='hero_sliders/mobile/',
            ),
        ),
    ]
