# Generated by Django 5.0.6 on 2026-04-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_discounted_price'),
        ('products', '0010_heroslider_mobile_image'),
    ]

    operations = [
    ]
